# In R ----------------------------------------
#' @useDynLib rGEDI
#' @export
gediSimulator <- function(
  input,
  output,
  inList = NULL,
  ground = FALSE,
  hdf = TRUE,
  waveID = NULL,

  coords = NULL,
  listCoord = NULL,
  gridBound = NULL,
  gridStep = 30.0,

  pSigma = -1.0,
  pFWHM = 15.0,
  readPulse = NULL,
  fSigma = 5.5,
  wavefront = NULL,
  res = 0.15,
  LVIS = FALSE,
  topHat = FALSE,
  sideLobe = FALSE,
  lobeAng = 0.0,

  checkCover = FALSE,
  maxScanAng = 1000000.0,
  decimate = 1.0,

  pBuff = as.integer(200000000),
  maxBins = as.integer(1024),
  countOnly = FALSE,
  pulseAfter = FALSE,
  pulseBefore = TRUE,
  noNorm = FALSE,

  noOctree = FALSE,
  octLevels = as.integer(0),
  nOctPix = as.integer(40),

  decon = FALSE,
  indDecon = FALSE,
  readWave = FALSE,

  listFiles = FALSE,
  keepOld = FALSE,
  useShadow = FALSE,
  polyGround = FALSE,
  nnGround = FALSE,
  seed = NULL) {
  .Call("C_gedisimulate",
      input,
      output,
      inList,
      ground,
      hdf,
      waveID,

      coords,
      listCoord,
      gridBound,
      gridStep,

      pSigma,
      pFWHM,
      readPulse,
      fSigma,
      wavefront,
      res,
      LVIS,
      topHat,
      sideLobe,
      lobeAng,

      checkCover,
      maxScanAng,
      decimate,

      as.integer(pBuff),
      as.integer(maxBins),
      countOnly,
      pulseAfter,
      pulseBefore,
      noNorm,

      noOctree,
      as.integer(octLevels),
      as.integer(nOctPix),

      decon,
      indDecon,
      readWave,

      listFiles,
      keepOld,
      useShadow,
      polyGround,
      nnGround,
      seed)
  return(hdf5r::H5File$new(output, "r+"))
}



#' @export
gediMetric <- function(
  input,
  writeFit = FALSE,
  writeGauss = FALSE,
  readBinLVIS = FALSE,
  readHDFlvis = FALSE,
  readHDFgedi = TRUE,
  level2 = NULL,
  bounds = NULL,
  ground = FALSE,
  useInt = FALSE,
  useFrac = FALSE,
  rhRes = 5,
  laiRes = 10.0,
  laiH = 30.0,
  noRHgauss = FALSE,
  gTol = 0.0,
  fhdHistRes = 0.001,
  forcePsigma = FALSE,
  bayesGround = FALSE,
  dontTrustGround = FALSE,
  noRoundCoord = FALSE,
  dcBias = NULL,
  nSig = 0.0,
  seed = NULL,
  hNoise = 0.0,
  linkNoise = NULL,
  linkFsig = 5.5,
  linkPsig = 0.764331,
  trueSig = 5.0,
  bitRate = NULL,
  maxDN = 4096.0,
  renoise = FALSE,
  newPsig = 1.0,
  oldPsig = 0.764331,
  addDrift = 0.0,
  missGround = 0,
  minGap = NULL,
  photonCount = FALSE,
  nPhotons = 2.1,
  photonWind = 200,
  noiseMult = 0.1,
  meanN = 0.0,
  thresh = 0.00000001,
  varNoise = FALSE,
  varScale = 1.5,
  statsLen = 30.0,
  noiseTrack = FALSE,
  sWidth = 0.0,
  psWidth = 0.0,
  msWidth = 0.0,
  preMatchF = FALSE,
  postMatchF = FALSE,
  pFile = NULL,
  gWidth = 1.2,
  minGsig = 0.764331,
  minWidth = 0,
  medNoise = FALSE,
  varDrift = FALSE,
  driftFac = NULL,
  varRhoG = 0.4,
  varRhoC = 0.57,
  pSigma = 1.0,
  gold = FALSE,
  deconTol = 0.0000001) {
  .Call("C_gediMetrics",
        input,
        writeFit,
        writeGauss,
        readBinLVIS,
        readHDFlvis,
        readHDFgedi,
        level2,
        bounds,
        ground,
        useInt,
        useFrac,
        rhRes,
        laiRes,
        laiH,
        noRHgauss,
        gTol,
        fhdHistRes,
        forcePsigma,
        bayesGround,
        dontTrustGround,
        noRoundCoord,
        dcBias,
        nSig,
        seed,
        hNoise,
        linkNoise,
        linkFsig,
        linkPsig,
        trueSig,
        bitRate,
        maxDN,
        renoise,
        newPsig,
        oldPsig,
        addDrift,
        missGround,
        minGap,
        photonCount,
        nPhotons,
        photonWind,
        noiseMult,
        meanN,
        thresh,
        varNoise,
        varScale,
        statsLen,
        noiseTrack,
        sWidth,
        psWidth,
        msWidth,
        preMatchF,
        postMatchF,
        pFile,
        gWidth,
        minGsig,
        minWidth,
        medNoise,
        varDrift,
        driftFac,
        varRhoG,
        varRhoC,
        pSigma,
        gold,
        deconTol)
  return(hdf5r::H5File$new(output, "r+"))
}
