#' @export
gediMetric <- function(
  input,
  outRoot,
  inList = NULL,
  writeFit = FALSE,
  writeGauss = FALSE,
  readBinLVIS = FALSE,
  readHDFlvis = FALSE,
  readHDFgedi = FALSE,
  level2 = NULL,
  bounds = NULL,
  beamList = NULL,
  skipBeams = NULL,
  readBeams = NULL,
  ground = FALSE,
  useInt = FALSE,
  useFrac = FALSE,
  rhRes = 5.0,
  laiRes = 10.0,
  laiH = 30.0,
  noRHgauss = FALSE,
  gTol = 0.0,
  fhdHistRes = 0.001,
  forcePsigma = FALSE,
  bayesGround = FALSE,
  dontTrustGround = FALSE,
  noRoundCoord = FALSE,
  noCanopy = FALSE,
  dcBias = 0.0,
  nSig = 0.0,
  seed = NULL,
  hNoise = 0.0,
  linkNoise = NULL,
  linkFsig = NULL,
  linkPsig = NULL,
  trueSig = NULL,
  bitRate = NULL,
  maxDN = NULL,
  renoise = FALSE,
  newPsig = -1.0,
  oldPsig = 0.764331,
  addDrift = NULL,
  missGround = FALSE,
  minGap = NULL,
  photonCount = FALSE,
  pcl = FALSE,
  nPhotons = 2.1,
  photonWind = 200.0,
  noiseMult = 0.1,
  rhoVrhoG = 1.0,
  nPhotC = 2.1,
  nPhotG = -1.0,
  photHDF = FALSE,
  meanN = 0.0,
  thresh = 0.00000000000001,
  varNoise = FALSE,
  varScale = NULL,
  statsLen = NULL,
  noiseTrack = FALSE,
  sWidth = NULL,
  psWidth = 0.0,
  msWidth = NULL,
  preMatchF = FALSE,
  postMatchF = FALSE,
  pFile = NULL,
  gWidth = 1.2,
  minGsig = 0.764331,
  minWidth = 0.0,
  medNoise = FALSE,
  varDrift = NULL,
  driftFac = NULL,
  rhoG = 0.4,
  rhoC = 0.57,
  pSigma = NULL,
  gold = FALSE,
  deconTol = NULL) {
  loadLibrary()
  .Call("C_gediMetrics",
        # Input output
        input,
        outRoot,
        inList,
        writeFit,
        writeGauss,
        readBinLVIS,
        readHDFlvis,
        readHDFgedi,
        level2,
        bounds,
        beamList,
        skipBeams,
        readBeams,

        # Switches
        ground,
        useInt,
        useFrac,
        rhRes,
        laiRes,
        laiH,
        noRHgauss,
        gTol,
        fhdHistRes,
        forcePsigma,
        bayesGround,
        dontTrustGround,
        noRoundCoord,
        noCanopy,

        # Adding noise
        dcBias,
        nSig,
        seed,
        hNoise,
        linkNoise,
        linkFsig,
        linkPsig,
        trueSig,
        bitRate,
        maxDN,
        renoise,
        newPsig,
        oldPsig,
        addDrift,
        missGround,
        minGap,

        # Photon Counting
        photonCount,
        pcl,
        nPhotons,
        photonWind,
        noiseMult,
        rhoVrhoG,
        nPhotC,
        nPhotG,
        photHDF,

        # Denoising
        meanN,
        thresh,
        varNoise,
        varScale,
        statsLen,
        noiseTrack,
        sWidth,
        psWidth,
        msWidth,
        preMatchF,
        postMatchF,
        pFile,
        list(gWidth,
        minGsig,
        minWidth,
        medNoise,
        varDrift,
        driftFac,
        rhoG,
        rhoC,
        pSigma,
        gold,
        deconTol))
  unloadLibrary()

  output = paste0(outRoot, ".metric.txt")
  header = read.csv(output, sep=",", nrow=1, header = FALSE, as.is=TRUE)
  header[ncol(header)] = NULL
  header=gsub(" *\\d+ *([^ ]*)", "\\1", header)

  metricData = read.csv(output, sep=" ", skip=1, na.strings = "?", header = FALSE)
  if (ncol(metricData) == length(header)) {
    names(metricData) = header
  }

  return (metricData)
}
